import json

d = json.load(open('scratch/w184_draft.json', encoding='utf-8'))

notes = (
    "ROUTE: Claude-in-Chrome connector only, one dedicated tab (tabId 1961718952), closed at the end. "
    "robots.txt fetched same-origin first (https://www.ikea.com/robots.txt): no anthropic-ai / ClaudeBot / "
    "Claude-Web / Claude-User / Claude-SearchBot directive anywhere, no blanket Disallow: /. No curl / "
    "requests / WebFetch / proxy at any point; every fetch() ran inside the loaded www.ikea.com/jp/ja page "
    "context (same-origin-style call to IKEA's own sik.search.blue.cdtapps.com API, the endpoint IKEA's own "
    "frontend calls). No 403, CAPTCHA, DataDome or rate-limit was seen at any stage.\n\n"
    "TREE SOURCE AND REUSE OF THE ESTABLISHED IKEA GLOBAL SET: script[type=text/hydrate] -> "
    "data.data.config.catalogSlim on https://www.ikea.com/jp/ja/cat/furniture-fu001/; the child key is "
    "'subs', per the project correction from IKEA DE (f107/qa_notes.md), NOT 'subCategories'. The JP payload "
    "has the identical 8 furniture-bearing top-level department ids already established by IKEA UK (f92), "
    "DE (f107), FR (f140) and UAE (f164) on this shared global platform: fu002 Tables & chairs, 700640 Sofas "
    "& armchairs, bm001 Beds & mattresses, st001 Storage & organisation, fu004 Desk & desk chairs, ba001 "
    "Bathroom products, od001 Outdoor products, bc001 Baby & children (721 node instances, 581 raw leaves "
    "under these 8 departments on the JP tree). Rather than re-deriving the furniture/non-furniture line from "
    "scratch, this pass reused IKEA UAE's (f164, SR164) already-adjudicated 117-leaf id set -- the same set "
    "IKEA DE (117) and FR (116) independently converged on -- since IKEA runs one global category-id scheme "
    "per the project's own established finding, and queried it against the jp/ja market.\n\n"
    "TRAP CHECK (mandatory nav-under-reports sweep, section 7b): the full 581-leaf JP tree under the 8 "
    "furniture departments was keyword-swept in Japanese (sofa/chair/stool/table/desk/bed/wardrobe/cabinet/"
    "cupboard/bench/sideboard/shelf/bookcase/dresser/chest/drawer/couch/trolley/vanity/console/nightstand/"
    "headboard/ottoman/pouf/futon/daybed/hammock terms), named-series product-line nodes (PAX, BESTA, PLATSA "
    "etc. -- identifiable by their Latin-caps-plus-katakana naming pattern, e.g. 'PAX/pakkusu') were excluded "
    "as component listings, and children of ids already covered by the 117-set were excluded (these are "
    "deeper seat-count/size cuts -- e.g. 2-seat vs 3-seat sofa splits of fu003 -- that DE/FR/AE all "
    "deliberately stopped above). This left 33 genuine candidates, ALL of which fall cleanly into exclusion "
    "categories already established project-wide: wall shelving (Wall Decor's job, ids in the 10398 branch), "
    "cabinet/closet LED lighting accessories (Lighting's job), a toy-box-and-shelf node (standalone storage), "
    "sofa/bed legs and covers (furniture parts), duvet covers/sheets/pillows/blankets (bedding textiles), "
    "mattress bases and crib mattresses, under-bed storage, desk organisers/partitions (office supplies), "
    "outdoor furniture covers, and desk/outdoor/bathroom decorative lighting. ZERO net-new furniture leaves "
    "were found -- this confirms the UAE-curated 117-id set transfers completely and exhaustively to the JP "
    "market with no JP-specific furniture node missed.\n\n"
    "QTY METHOD (matches f107/f140/f164 convention exactly): for every leaf, qty = "
    "productListPage.productCount from sik.search.blue.cdtapps.com/jp/ja/product-list-page?category=<id>, "
    "fetched from the loaded page. IKEA's rendered listing header is inflated by +1 whenever plannerCount>0 "
    "(a non-product planner tile injected by client-side hydration) -- this same offset was measured on DE, "
    "FR and AE and is not re-measured here; the header figure (productCount+1 when plannerCount>0) is stated "
    "in every evidence string alongside qty so either convention stays recoverable. 65 of the 113 JP leaves "
    "have plannerCount>0. NODE IDENTITY: unlike the AE response, the JP product-list-page API DOES echo "
    "category.name and category.url (matching the DE/FR pattern) -- every single leaf's identity was "
    "confirmed this way: the API's own category.name (Japanese) was translated and cross-checked against the "
    "id's standing DE/FR/AE label, and its category.url exactly matched the expected https://www.ikea.com/jp/"
    "ja/cat/<slug>-<id>/ pattern with the SAME slug used on ae/en, de/de and fr/fr for that id (spot-checked "
    "across the full set) -- no id silently resolved to a different or parent node.\n\n"
    "MARKET COVERAGE: 113 of the 117 shared ids resolved live on JP with HTTP 200. 4 returned HTTP 404 "
    "'Unknown category key' from the sik.search API on the jp/ja market specifically and are EXCLUDED from "
    "this file (dropped, not emitted as null-qty rows, since there is no live listing page to link to): "
    "25206 Wall-Mounted Tables, 47360 Bar Table Sets, 700424 Conference Table & Chair Sets, 55021 Nursery "
    "Furniture Sets. This is the same class of single-market gap already documented on every other IKEA "
    "store (UK/DE/FR/AE each miss a different 1-2 ids from the shared set), not a JP-specific failure. "
    "Removing these 4 leaves left every parent grouping row with at least one surviving child (verified "
    "programmatically), so no grouping row was dropped.\n\n"
    "NAMING: the JP storefront is Japanese-only. Every leaf's sub_category is the JP site's own live "
    "category.name, translated to English. In the large majority of cases the translation matches the "
    "standing DE/FR/AE label for that shared id and that label is used directly (translation, not "
    "invention, per the project's own-wording rule). Three rows show a genuine JP-specific wording "
    "divergence from AE and use JP's own translated wording instead, flagged individually: 21962 (JP "
    "'Outdoor Lounge Chairs' vs AE's corrected 'Outdoor Armchairs'), 21967 (JP's own clean 'Garden Table "
    "Sets', avoiding the collision AE worked around via slug wording), and 21959 (JP's own generic "
    "'Lounging & Relaxing Furniture' wording kept, per AE's cross-market content verification that this id "
    "lists outdoor sofas, not independently re-verified here).\n\n"
    "FLAGGED ROWS (7): four carry forward mixed-node / ambiguous-node findings AE (f164) already "
    "established on these SAME shared global category ids (Shoe Cabinets id 10456, Basket Drawer Units id "
    "46081, Outdoor Storage id 21958, Laptop Tables id 24830) -- these are catalogue-structural properties "
    "of the shared IKEA taxonomy, not market-specific, so they were not independently re-verified by opening "
    "JP product tiles. Three are the JP label-divergence rows above (Lounging & Relaxing Furniture, Outdoor "
    "Lounge Chairs, Garden Table Sets).\n\n"
    "INDEPENDENCE FROM IKEA DE (f107) / FR (f140) / AE (f164): every compared figure differs, confirming JP "
    "runs its own market inventory on the shared global platform (same finding the prior Home-Decor pass on "
    "this exact company, archive c213, already established): Dining Tables DE 92 / FR 86 / AE 61 / JP 64; "
    "Sofas DE 274 / FR 227 / AE 226 / JP 212; Beds DE 226 / FR 232 / AE 208 / JP 189; Fitted Wardrobes DE "
    "389 / FR 403 / AE 348 / JP 192; Dining Chairs DE 112 / FR 110 / AE 109 / JP 109 (near-coincidental "
    "match, not a copy -- Bookcases DE/FR/AE all differ from JP's 122, ruling out a shared-fixture bug).\n\n"
    "EXCLUDED, and why (same platform-wide taxonomy as UK/DE/FR/AE): the whole named-series/product-line "
    "layer (PAX, BESTA, PLATSA, IVAR, BROR, SMASTAD, RELATERA, desk systems, bathroom series etc. -- "
    "component listings); mattresses and bed bases; bedding and textiles (duvet covers, sheets, pillows, "
    "blankets, bed covers); furniture parts, covers and care (sofa/bed legs, bed base and headboard covers, "
    "chair covers, outdoor furniture covers); standalone storage goods (toy boxes, under-bed storage, small "
    "item storage st007); wall shelving (Wall Decor's job); bathroom fixtures and mirrors (sinks, taps, "
    "showers, bathroom mirrors); laundry goods except the one cabinet-furniture node (Laundry Storage, kept); "
    "lighting of every kind including cabinet/closet accent lighting; decoration, tableware, plants and pots, "
    "toys, baby care, picnic/bag goods, outdoor non-furniture (parasols, outdoor kitchens, flooring, grill "
    "accessories); and the fitted-kitchen tree (ka001). The two furniture nodes IKEA files inside the "
    "kitchen/storage trees -- Kitchen Islands & Trolleys and Pantry -- ARE included, matching AE.\n\n"
    "SANITY CHECKS: 65 distinct qty values observed across 113 leaves (range 1-212), no site-wide constant "
    "and no suspiciously round display cap; every id's h1/category.name matched its expected node (see "
    "identity check above); no leaf returned a round number suggestive of a display cap; Console Tables (id "
    "16246) legitimately reads 1 product on JP, consistent with the same id reading low counts on other "
    "markets."
)

d['notes'] = notes
json.dump(d, open('f184.json', 'w', encoding='utf-8'), ensure_ascii=False, indent=1)
print("wrote f184.json")
print(d['status'], len(d['rows']))
