# -*- coding: utf-8 -*-
# Row definitions for OTTO Home (SR131) Textile + Storage extraction.
# Each row: (array, is_group, name, url_or_None, confidence, note)
BASE = "https://www.otto.de"

TEXTILE_ROWS = [
    ("group", "Heimtextilien (Home Textiles)", None, None, None),
    ("leaf", "Cushion Pads / Seat Pads (Auflagen)", "/heimtextilien/auflagen/", "MEDIUM", None),
    ("leaf", "Bath Mats", "/heimtextilien/badematten/", "HIGH", None),

    ("group", "Duvets (Bettdecken)", None, None, None),
    ("leaf", "Duvet Sets", "/heimtextilien/bettdecken/bettdecken-sets/", "HIGH", None),
    ("leaf", "Feather Duvets", "/heimtextilien/bettdecken/federbetten/", "HIGH", None),
    ("leaf", "Microfiber Duvets", "/heimtextilien/bettdecken/microfaserbettdecken/", "HIGH", None),
    ("leaf", "Natural Fiber Duvets", "/heimtextilien/bettdecken/naturfaserdecken/", "HIGH", None),
    ("leaf", "Underblankets", "/heimtextilien/bettdecken/unterbetten/", "MEDIUM", None),

    ("group", "Bed Sheets (Bettlaken)", None, None, None),
    ("leaf", "Flat Sheets", "/heimtextilien/bettlaken/betttuecher/", "HIGH", None),
    ("leaf", "Fitted Sheets", "/heimtextilien/bettlaken/spannbettlaken/", "HIGH", None),

    ("group", "Bed Linen (Bettwaesche)", None, None, None),
    ("leaf", "Duvet Covers", "/heimtextilien/bettwaesche/bettdeckenbezuege/", "HIGH", None),
    ("leaf", "Bed Linen Sets", "/heimtextilien/bettwaesche/bettwaesche-sets/", "HIGH", None),
    ("leaf", "Pillowcases", "/heimtextilien/bettwaesche/kopfkissenbezuege/", "HIGH", None),

    ("leaf", "Covers (Bezuege)", "/heimtextilien/bezuege/", "MEDIUM", None),
    ("leaf", "Ironing Board Covers", "/heimtextilien/buegeltuecher/", "LOW", None),

    ("group", "Doormats (Fussmatten)", None, None, None),
    ("leaf", "Dirt-Trapping Runners", "/heimtextilien/fussmatten/schmutzfanglaeufer/", "HIGH", None),

    ("group", "Curtains (Gardinen)", None, None, None),
    ("leaf", "Thread Curtains", "/heimtextilien/gardinen/fadenvorhaenge/", "HIGH", None),
    ("leaf", "Ready Made Curtains", "/heimtextilien/gardinen/fertiggardinen/", "HIGH", None),
    ("leaf", "Curtain Sets", "/heimtextilien/gardinen/gardinen-sets/", "HIGH", None),
    ("group", "Curtain Fabric (Gardinenstoffe)", None, None, None),
    ("leaf", "Thermal Curtain Fabric", "/heimtextilien/gardinen/gardinenstoffe/thermostoffe/", "HIGH", None),
    ("leaf", "Blackout Curtain Fabric", "/heimtextilien/gardinen/gardinenstoffe/verdunkelungsstoffe/", "HIGH", None),
    ("leaf", "Curtain Voiles/Sheers", "/heimtextilien/gardinen/gardinenstores/", "HIGH", None),
    ("leaf", "Curtain Valances", "/heimtextilien/gardinen/querbehaenge/", "HIGH", None),
    ("group", "Austrian/Roman Blinds (Raffrollos)", None, None, None),
    ("leaf", "Ribbon Roman Blinds", "/heimtextilien/gardinen/raffrollos/baendchenrollos/", "MEDIUM", None),
    ("leaf", "Tie-Up Curtains", "/heimtextilien/gardinen/raffrollos/bindegardinen/", "MEDIUM", None),
    ("leaf", "Magnetic Roman Blinds", "/heimtextilien/gardinen/raffrollos/magnetrollos/", "MEDIUM", None),
    ("group", "Cafe Curtains (Scheibengardinen)", None, None, None),
    ("leaf", "Cafe Curtain Sets", "/heimtextilien/gardinen/scheibengardinen/scheibengardinen-sets/", "HIGH", None),
    ("group", "Panel Curtains (Schiebegardinen)", None, None, None),
    ("leaf", "Panel Curtain Sets", "/heimtextilien/gardinen/schiebegardinen/schiebegardinen-sets/", "HIGH", None),
    ("leaf", "Door Curtains", "/heimtextilien/gardinen/tuervorhaenge/", "HIGH", None),

    ("group", "Towels (Handtuecher)", None, None, None),
    ("leaf", "Bath Towels", "/heimtextilien/handtuecher/badetuecher/", "HIGH", None),
    ("leaf", "Guest Towels", "/heimtextilien/handtuecher/gaestehandtuecher/", "HIGH", None),
    ("leaf", "Towel Sets", "/heimtextilien/handtuecher/handtuch-sets/", "HIGH", None),
    ("group", "Sauna Towels (Saunatuecher)", None, None, None),
    ("leaf", "Hammam Towels", "/heimtextilien/handtuecher/saunatuecher/hamamtuecher/", "MEDIUM", None),
    ("leaf", "Sarongs", "/heimtextilien/handtuecher/saunatuecher/sarongs/", "MEDIUM", None),
    ("leaf", "Sauna Kilts", "/heimtextilien/handtuecher/saunatuecher/saunakilts/", "MEDIUM", None),
    ("leaf", "Beach Towels", "/heimtextilien/handtuecher/strandtuecher/", "HIGH", None),
    ("leaf", "Wash Mitts", "/heimtextilien/handtuecher/waschhandschuhe/", "HIGH", None),
    ("group", "Washcloths (Waschlappen)", None, None, None),
    ("leaf", "Soap Cloths", "/heimtextilien/handtuecher/waschlappen/seiftuecher/", "MEDIUM", None),

    ("group", "Furniture Covers/Slipcovers (Hussen)", None, None, None),
    ("leaf", "Bed Covers", "/heimtextilien/hussen/betthussen/", "MEDIUM", None),
    ("leaf", "Slipcover Sets", "/heimtextilien/hussen/hussen-sets/", "HIGH", None),
    ("leaf", "Armchair Slipcovers", "/heimtextilien/hussen/sesselhussen/", "HIGH", None),
    ("leaf", "Armchair Protectors", "/heimtextilien/hussen/sesselschoner/", "HIGH", None),
    ("leaf", "Sofa Slipcovers", "/heimtextilien/hussen/sofahussen/", "HIGH", None),
    ("leaf", "Sofa Protectors", "/heimtextilien/hussen/sofaschoner/", "HIGH", None),
    ("leaf", "Sofa Throws/Covers", "/heimtextilien/hussen/sofaueberwuerfe/", "HIGH", None),
    ("leaf", "Chair Slipcovers", "/heimtextilien/hussen/stuhlhussen/", "HIGH", None),
    ("leaf", "Table Slipcovers", "/heimtextilien/hussen/tischhussen/", "HIGH", None),

    ("group", "Cushions (Kissen)", None, None, None),
    ("group", "Floor Cushions (Bodenkissen)", None, None, None),
    ("leaf", "Floor Seat Cushions", "/heimtextilien/kissen/bodenkissen/bodensitzkissen/", "HIGH", None),
    ("leaf", "Decorative Cushions", "/heimtextilien/kissen/dekokissen/", "HIGH", None),
    ("leaf", "Scented Cushions", "/heimtextilien/kissen/duftkissen/", "MEDIUM", None),
    ("group", "Head Pillows (Kopfkissen)", None, None, None),
    ("leaf", "3-Chamber Pillows", "/heimtextilien/kissen/kopfkissen/3-kammer-kopfkissen/", "HIGH", None),
    ("leaf", "Water Pillows", "/heimtextilien/kissen/kopfkissen/wasserkissen/", "HIGH", None),
    ("group", "Neck Cushions (Nackenkissen)", None, None, None),
    ("leaf", "Headrest Cushions", "/heimtextilien/kissen/nackenkissen/kopfstuetzkissen/", "HIGH", None),
    ("leaf", "Neck Horn Cushions", "/heimtextilien/kissen/nackenkissen/nackenhoernchen/", "HIGH", None),
    ("leaf", "Bolster Cushions", "/heimtextilien/kissen/nackenkissen/nackenrollen/", "HIGH", None),
    ("leaf", "Back Cushions", "/heimtextilien/kissen/rueckenkissen/", "HIGH", None),
    ("group", "Seat Cushions (Sitzkissen)", None, None, None),
    ("leaf", "Wedge Cushions", "/heimtextilien/kissen/sitzkissen/keilkissen/", "HIGH", None),
    ("leaf", "Chair Cushions", "/heimtextilien/kissen/sitzkissen/stuhlkissen/", "HIGH", None),

    ("group", "Cushion/Pillow Covers (Kissenbezuege)", None, None, None),
    ("leaf", "Bolster Covers", "/heimtextilien/kissenbezuege/nackenrollenbezuege/", "HIGH", None),
    ("leaf", "Side-Sleeper Pillow Covers", "/heimtextilien/kissenbezuege/seitenschlaeferkissenbezuege/", "HIGH", None),
    ("leaf", "Nursing Pillow Covers", "/heimtextilien/kissenbezuege/stillkissenbezuege/", "HIGH", None),

    ("leaf", "Knee Cushions", "/heimtextilien/kniekissen/", "LOW", None),

    ("group", "Mattress Protection (Matratzenschutz)", None, None, None),
    ("leaf", "Encasings (Allergy Mattress Covers)", "/heimtextilien/matratzen/matratzenschutz/encasings/", "HIGH", None),
    ("leaf", "Mattress Covers", "/heimtextilien/matratzen/matratzenschutz/matratzenbezuege/", "HIGH", None),
    ("leaf", "Mattress Wedges", "/heimtextilien/matratzen/matratzenschutz/matratzenkeile/", "LOW", None),
    ("leaf", "Mattress Protectors", "/heimtextilien/matratzen/matratzenschutz/matratzenschoner/", "HIGH", None),
    ("group", "Mattress Toppers (Topper)", None, None, None),
    ("leaf", "Gel Foam Toppers", "/heimtextilien/matratzen/topper/gelschaum-topper/", "HIGH", None),
    ("leaf", "Cold Foam Toppers", "/heimtextilien/matratzen/topper/kaltschaum-topper/", "HIGH", None),
    ("leaf", "Comfort Foam Toppers", "/heimtextilien/matratzen/topper/komfortschaum-topper/", "HIGH", None),
    ("leaf", "Visco Foam Toppers", "/heimtextilien/matratzen/topper/visco-topper/", "HIGH", None),

    ("group", "Cot Bumpers (Nestchen)", None, None, None),
    ("leaf", "Bed Draft Stoppers", "/heimtextilien/nestchen/nestchenschlangen/", "MEDIUM", None),

    ("group", "Roller & Pleated Blinds (Rollos-Plissees)", None, None, None),
    ("leaf", "Vertical Louvre Blinds", "/heimtextilien/rollos-plissees/lamellenvorhaenge/", "LOW", None),
    ("group", "Pleated Blinds (Plissees)", None, None, None),
    ("leaf", "Sun Protection Pleated Blinds", "/heimtextilien/rollos-plissees/plissees/sonnenschutz-plissees/", "HIGH", None),
    ("group", "Roller Blinds (Rollos)", None, None, None),
    ("leaf", "Double Roller Blinds", "/heimtextilien/rollos-plissees/rollos/doppelrollos/", "HIGH", None),
    ("leaf", "Side-Pull Roller Blinds", "/heimtextilien/rollos-plissees/rollos/seitenzugrollos/", "HIGH", None),
    ("leaf", "Spring Roller Blinds", "/heimtextilien/rollos-plissees/rollos/springrollos/", "HIGH", None),
    ("leaf", "Blackout Roller Blinds", "/heimtextilien/rollos-plissees/rollos/verdunkelungsrollos/", "HIGH", None),

    ("group", "Aprons (Schuerzen)", None, None, None),
    ("leaf", "Smock Aprons", "/heimtextilien/schuerzen/kittelschuerzen/", "HIGH", None),
    ("leaf", "Cooking Aprons", "/heimtextilien/schuerzen/kochschuerzen/", "HIGH", None),
    ("leaf", "Bib Aprons", "/heimtextilien/schuerzen/latzschuerzen/", "HIGH", None),

    ("group", "Rugs (Teppiche)", None, None, None),
    ("group", "Fur/Sheepskin Rugs (Fellteppiche)", None, None, None),
    ("leaf", "Faux Fur Rugs", "/heimtextilien/teppiche/fellteppiche/kunstfell-teppiche/", "HIGH", None),
    ("leaf", "Flatweave Rugs", "/heimtextilien/teppiche/flachgewebe-teppiche/", "HIGH", None),
    ("group", "High Pile Rugs (Hochflor-Teppiche)", None, None, None),
    ("leaf", "Flokati Rugs", "/heimtextilien/teppiche/hochflor-teppiche/flokati-teppiche/", "HIGH", None),
    ("leaf", "Shaggy Rugs", "/heimtextilien/teppiche/hochflor-teppiche/shaggy-teppiche/", "HIGH", None),
    ("leaf", "Short Pile Rugs", "/heimtextilien/teppiche/kurzflor-teppiche/", "HIGH", None),
    ("group", "Runners (Laeufer)", None, None, None),
    ("leaf", "Bedside Rug Sets", "/heimtextilien/teppiche/laeufer/bettumrandungen/", "HIGH", None),
    ("leaf", "High Pile Runners", "/heimtextilien/teppiche/laeufer/hochflor-laeufer/", "HIGH", None),
    ("leaf", "Short Pile Runners", "/heimtextilien/teppiche/laeufer/kurzflor-laeufer/", "HIGH", None),
    ("leaf", "Stair Tread Mats", "/heimtextilien/teppiche/stufenmatten/", "HIGH", None),
    ("leaf", "Rug Underlays", "/heimtextilien/teppiche/teppichunterlagen/", "MEDIUM", None),
    ("leaf", "Wall Tapestries", "/heimtextilien/teppiche/wandteppiche/", "HIGH", None),
    ("leaf", "Tent Carpets", "/heimtextilien/teppiche/zeltteppiche/", "MEDIUM", None),

    ("group", "Tablecloths (Tischdecken)", None, None, None),
    ("leaf", "Table Centerpiece Cloths", "/heimtextilien/tischdecken/mitteldecken/", "HIGH", None),
    ("leaf", "Placemats", "/heimtextilien/tischdecken/tischsets/", "HIGH", None),

    ("leaf", "Table Linens", "/heimtextilien/tischwaesche/", "HIGH", None),

    ("group", "Throws/Blankets (Wohndecken)", None, None, None),
    ("leaf", "Swaddle/Wrap Blankets", "/heimtextilien/wohndecken/einschlagdecken/", "HIGH", None),
    ("leaf", "Faux Fur Blankets", "/heimtextilien/wohndecken/kunstfelldecken/", "HIGH", None),
    ("leaf", "Cuddle Blankets/Throws", "/heimtextilien/wohndecken/kuscheldecken/", "HIGH", None),
    ("leaf", "Plaids/Throws", "/heimtextilien/wohndecken/plaids/", "HIGH", None),
    ("leaf", "Knitted Blankets", "/heimtextilien/wohndecken/strickdecken/", "HIGH", None),
    ("leaf", "Bedspreads", "/heimtextilien/wohndecken/tagesdecken/", "HIGH", None),

    ("group", "Textile Accessories (Zubehoer)", None, None, None),
    ("leaf", "Cushion Fillings/Inserts", "/heimtextilien/zubehoer/kissenfuellungen/", "MEDIUM", None),
]

STORAGE_ROWS = [
    ("group", "Storage (Aufbewahrung)", None, None, None),
    ("leaf", "Storage Trays", "/dekoration/aufbewahrung/ablagen/", "MEDIUM", None),
    ("leaf", "Storage Bowls", "/dekoration/aufbewahrung/aufbewahrungsschalen/", "MEDIUM", None),
    ("group", "Storage Bags (Aufbewahrungstaschen)", None, None, None),
    ("leaf", "Under-Bed Storage Bags", "/dekoration/aufbewahrung/aufbewahrungstaschen/betttaschen/", "HIGH", None),
    ("leaf", "Storage Trolleys", "/dekoration/aufbewahrung/aufbewahrungswagen/", "HIGH", None),
    ("group", "Storage Boxes (Boxen)", None, None, None),
    ("leaf", "Storage Boxes", "/dekoration/aufbewahrung/boxen/aufbewahrungsboxen/", "HIGH", None),
    ("leaf", "Folding Storage Boxes", "/dekoration/aufbewahrung/boxen/faltboxen/", "HIGH", None),
    ("leaf", "Photo Storage Boxes", "/dekoration/aufbewahrung/boxen/fotoboxen/", "MEDIUM", None),
    ("leaf", "Organization Boxes", "/dekoration/aufbewahrung/boxen/ordnungsboxen/", "HIGH", None),
    ("leaf", "Drawer Boxes", "/dekoration/aufbewahrung/boxen/schubladenboxen/", "HIGH", None),
    ("leaf", "Shoe Storage Boxes", "/dekoration/aufbewahrung/boxen/schuhboxen/", "HIGH", None),
    ("leaf", "Stackable Storage Boxes", "/dekoration/aufbewahrung/boxen/stapelboxen/", "HIGH", None),
    ("leaf", "Storage Cases (Etuis)", "/dekoration/aufbewahrung/etuis/", "LOW", None),
    ("leaf", "Bottle Holders", "/dekoration/aufbewahrung/flaschenhalter/", "MEDIUM", None),
    ("leaf", "Wardrobe/Coat Storage Holders", "/dekoration/aufbewahrung/garderobenhalter/", "MEDIUM", None),
    ("group", "Storage Crates (Kisten)", None, None, None),
    ("leaf", "Toy Storage Crates", "/dekoration/aufbewahrung/kisten/spielzeugkisten/", "HIGH", None),
    ("group", "Storage Baskets (Koerbe)", None, None, None),
    ("leaf", "Decorative Storage Baskets", "/dekoration/aufbewahrung/koerbe/dekokoerbe/", "LOW", None),
    ("leaf", "Wire Storage Baskets", "/dekoration/aufbewahrung/koerbe/drahtkoerbe/", "HIGH", None),
    ("leaf", "Bottle Baskets", "/dekoration/aufbewahrung/koerbe/flaschenkoerbe/", "MEDIUM", None),
    ("leaf", "Woven Storage Baskets", "/dekoration/aufbewahrung/koerbe/flechtkoerbe/", "HIGH", None),
    ("leaf", "Hanging Storage Baskets", "/dekoration/aufbewahrung/koerbe/haengekoerbe/", "MEDIUM", None),
    ("leaf", "Sewing Boxes", "/dekoration/aufbewahrung/koerbe/naehkaestchen/", "MEDIUM", None),
    ("leaf", "Shelf Storage Baskets", "/dekoration/aufbewahrung/koerbe/regalkoerbe/", "HIGH", None),
    ("leaf", "Stair Storage Baskets", "/dekoration/aufbewahrung/koerbe/treppenkoerbe/", "MEDIUM", None),
    ("leaf", "Umbrella Stands", "/dekoration/aufbewahrung/schirmstaender/", "MEDIUM", None),
    ("group", "Key Storage (Schluesselaufbewahrung)", None, None, None),
    ("leaf", "Key Boards", "/dekoration/aufbewahrung/schluesselaufbewahrung/schluesselbretter/", "HIGH", None),
    ("leaf", "Key Boxes", "/dekoration/aufbewahrung/schluesselaufbewahrung/schluesselkaesten/", "HIGH", None),
    ("group", "Jewelry Storage (Schmuckaufbewahrung)", None, None, None),
    ("leaf", "Glasses Cases", "/dekoration/aufbewahrung/schmuckaufbewahrung/brillenetuis/", "LOW", None),
    ("leaf", "Watch Boxes", "/dekoration/aufbewahrung/schmuckaufbewahrung/uhrenboxen/", "HIGH", None),
    ("group", "Jewelry Storage (Schmuckaufbewahrungen)", None, None, None),
    ("leaf", "Jewelry Holders", "/dekoration/aufbewahrung/schmuckaufbewahrungen/schmuckhalter/", "HIGH", None),
    ("leaf", "Jewelry Boxes", "/dekoration/aufbewahrung/schmuckaufbewahrungen/schmuckkaesten/", "HIGH", None),
    ("leaf", "Jewelry Cases", "/dekoration/aufbewahrung/schmuckaufbewahrungen/schmuckkoffer/", "HIGH", None),
    ("leaf", "Jewelry Stands", "/dekoration/aufbewahrung/schmuckaufbewahrungen/schmuckstaender/", "HIGH", None),
    ("group", "Drawer Inserts (Schubladeneinsaetze)", None, None, None),
    ("leaf", "Cutlery Inserts", "/dekoration/aufbewahrung/schubladeneinsaetze/besteckeinsaetze/", "HIGH", None),
    ("leaf", "Storage Chests/Trunks", "/dekoration/aufbewahrung/truhen/", "HIGH", None),
    ("leaf", "Over-Door Racks", "/dekoration/aufbewahrung/tuerregale/", "HIGH", None),
    ("leaf", "Under-Bed Storage Drawers", "/dekoration/aufbewahrung/unterbettkommoden/", "HIGH", None),
    ("leaf", "Wall Hooks (Storage)", "/dekoration/aufbewahrung/wandhaken/", "MEDIUM", None),
    ("leaf", "Wine Bottle Holders", "/dekoration/aufbewahrung/weinflaschenhalter/", "MEDIUM", None),
    ("leaf", "Newspaper/Magazine Stands", "/dekoration/aufbewahrung/zeitungsstaender/", "HIGH", None),

    ("group", "Kitchen Storage (Kuechenaufbewahrung)", None, None, None),
    ("leaf", "Cutlery Holders", "/haushalt/kuechenaufbewahrung/besteckhalter/", "HIGH", None),
    ("leaf", "Egg Storage Boxes", "/haushalt/kuechenaufbewahrung/eierboxen/", "LOW", None),
    ("leaf", "Bottle Organizers", "/haushalt/kuechenaufbewahrung/flaschensammler/", "HIGH", None),
    ("leaf", "Hanging Rails (Kitchen Storage)", "/haushalt/kuechenaufbewahrung/haengeleisten/", "MEDIUM", None),
    ("group", "Household Shelving (Haushaltsregale)", None, None, None),
    ("leaf", "Clamp/Tension Shelves", "/haushalt/kuechenaufbewahrung/haushaltsregale/klemmregale/", "HIGH", None),
    ("leaf", "Kitchen Organizers", "/haushalt/kuechenaufbewahrung/kuechenorganizer/", "HIGH", None),
    ("leaf", "Kitchen Cabinet Baskets", "/haushalt/kuechenaufbewahrung/kuechenschrankkoerbe/", "HIGH", None),
    ("leaf", "Preserving Jars", "/haushalt/kuechenaufbewahrung/lebensmittelaufbewahrung/einmachglaeser/", "MEDIUM", None),
    ("leaf", "Organization Trolleys", "/haushalt/kuechenaufbewahrung/ordnungswagen/", "HIGH", None),
    ("leaf", "Roll Holders", "/haushalt/kuechenaufbewahrung/rollenhalter/", "LOW", None),

    ("group", "Food Storage (Lebensmittelaufbewahrung)", None, None, None),
    ("leaf", "Bread Bins", "/haushalt/koch-backzubehoer/lebensmittelaufbewahrung/brotkaesten/", "HIGH", None),
    ("leaf", "Storage Tins/Containers", "/haushalt/koch-backzubehoer/lebensmittelaufbewahrung/dosen/", "HIGH", None),
    ("leaf", "Reusable Food Storage Lids", "/haushalt/koch-backzubehoer/lebensmittelaufbewahrung/frischhaltedeckel/", "LOW", None),
    ("leaf", "Fresh-Keeping Storage Containers", "/haushalt/koch-backzubehoer/lebensmittelaufbewahrung/frischhaltedosen/", "HIGH", None),
    ("leaf", "Reusable Vegetable Storage Bags", "/haushalt/koch-backzubehoer/lebensmittelaufbewahrung/gemuesebeutel/", "LOW", None),
    ("leaf", "Spice Racks", "/haushalt/koch-backzubehoer/lebensmittelaufbewahrung/gewuerzregale/", "HIGH", None),
    ("leaf", "Spice Stands", "/haushalt/koch-backzubehoer/lebensmittelaufbewahrung/gewuerzstaender/", "HIGH", None),
    ("leaf", "Honey Storage Jars", "/haushalt/koch-backzubehoer/lebensmittelaufbewahrung/honigglaeser/", "MEDIUM", None),
    ("leaf", "Coffee Storage Tins", "/haushalt/koch-backzubehoer/lebensmittelaufbewahrung/kaffeedosen/", "HIGH", None),
    ("leaf", "Cookie Storage Tins", "/haushalt/koch-backzubehoer/lebensmittelaufbewahrung/keksdosen/", "HIGH", None),
    ("leaf", "Cake Storage/Transport Boxes", "/haushalt/koch-backzubehoer/lebensmittelaufbewahrung/kuchenbehaelter/kuchentransportboxen/", "MEDIUM", None),
    ("leaf", "Lunch Boxes", "/haushalt/koch-backzubehoer/lebensmittelaufbewahrung/lunchboxen/", "HIGH", None),
    ("leaf", "Jam Storage Jars", "/haushalt/koch-backzubehoer/lebensmittelaufbewahrung/marmeladenglaeser/", "MEDIUM", None),
    ("leaf", "Muesli Storage Tins", "/haushalt/koch-backzubehoer/lebensmittelaufbewahrung/mueslidosen/", "HIGH", None),
    ("leaf", "Salad Storage Boxes", "/haushalt/koch-backzubehoer/lebensmittelaufbewahrung/salatboxen/", "HIGH", None),
    ("leaf", "Salt Storage Containers", "/haushalt/koch-backzubehoer/lebensmittelaufbewahrung/salzbehaelter/", "HIGH", None),
    ("leaf", "Tea Storage Tins", "/haushalt/koch-backzubehoer/lebensmittelaufbewahrung/teedosen/", "HIGH", None),
    ("leaf", "Thermal Storage Containers", "/haushalt/koch-backzubehoer/lebensmittelaufbewahrung/thermobehaelter/", "MEDIUM", None),
    ("leaf", "Transport Trolleys", "/haushalt/koch-backzubehoer/lebensmittelaufbewahrung/transportroller/", "LOW", None),
    ("leaf", "Storage Canisters", "/haushalt/koch-backzubehoer/lebensmittelaufbewahrung/vorratsdosen/", "HIGH", None),
    ("leaf", "Storage Jars", "/haushalt/koch-backzubehoer/lebensmittelaufbewahrung/vorratsglaeser/", "HIGH", None),

    ("group", "Clothes Storage (Kleideraufbewahrung)", None, None, None),
    ("leaf", "Garment Storage Covers", "/haushalt/waeschepflege/kleideraufbewahrung/kleiderhuellen/", "HIGH", None),

    ("group", "Laundry Storage (Waeschesammler)", None, None, None),
    ("leaf", "Laundry Boxes", "/haushalt/waeschepflege/waeschesammler/waescheboxen/", "HIGH", None),
    ("leaf", "Laundry Baskets", "/haushalt/waeschepflege/waeschesammler/waeschekoerbe/", "HIGH", None),

    ("group", "Garden Storage", None, None, None),
    ("leaf", "Garden Tool Holders", "/garten/aufbewahrung/gartengeraetehalter/", "MEDIUM", None),
    ("leaf", "Garden Shelving", "/garten/gartenaufbewahrung/gartenregale/", "HIGH", None),
    ("leaf", "Tool Cabinets", "/garten/gartenaufbewahrung/geraeteschraenke/", "HIGH", None),
    ("leaf", "Garden Sheds", "/garten/gartenaufbewahrung/geraeteschuppen/", "HIGH", None),
    ("leaf", "Waste Bin Storage Boxes", "/garten/gartenaufbewahrung/muelltonnenboxen/", "MEDIUM", None),
    ("leaf", "Cushion Storage Boxes (Garden)", "/garten/gartenmoebel/auflagenboxen/", "HIGH", None),
]
