TEXTILE = {
"Bed Pillows": "https://www.birchlane.com/bedding/sb0/bed-pillows-c1869348.html",
"Bed Skirts": "https://www.birchlane.com/bedding/sb0/bed-skirts-c1859494.html",
"Bedding Sets": "https://www.birchlane.com/bedding/sb0/bedding-sets-singles-c1862543.html",
"Comforters & Sets": "https://www.birchlane.com/bedding/sb0/comforters-sets-c1874122.html",
"Duvet Covers & Sets": "https://www.birchlane.com/bedding/sb0/duvet-covers-sets-c1859493.html",
"Duvet Inserts": "https://www.birchlane.com/bedding/sb0/duvet-inserts-c1854614.html",
"Mattress Pads & Toppers": "https://www.birchlane.com/bedding/sb0/mattress-pads-toppers-c1870464.html",
"Pillow Shams": "https://www.birchlane.com/bedding/sb0/pillow-shams-c1859492.html",
"Quilts, Coverlets & Sets": "https://www.birchlane.com/bedding/sb0/quilts-coverlets-sets-c1805536.html",
"Sheets & Pillowcases": "https://www.birchlane.com/bedding/sb0/sheets-pillowcases-c1859491.html",
"Bath Rugs & Mats": "https://www.birchlane.com/bathroom/sb0/bath-rugs-mats-c1854663.html",
"Bath Towels": "https://www.birchlane.com/bathroom/sb0/bath-towels-c1867187.html",
"Bathrobes": "https://www.birchlane.com/bathroom/sb0/bathrobes-c1869350.html",
"Shower Curtains": "https://www.birchlane.com/bathroom/sb0/shower-curtains-c1830148.html",
"Area Rugs": "https://www.birchlane.com/rugs/cat/area-rugs-c1805524.html",
"Indoor Rugs": "https://www.birchlane.com/rugs/sb0/indoor-rugs-c1875731.html",
"Outdoor Rugs": "https://www.birchlane.com/rugs/sb0/outdoor-rugs-c1805527.html",
"Runner Rugs": "https://www.birchlane.com/rugs/sb0/runner-rugs-c1868620.html",
"Doormats": "https://www.birchlane.com/rugs/sb0/doormats-c1863123.html",
"4 x 6 Rugs": "https://www.birchlane.com/rugs/sb0/4-x-6-rugs-c1873953.html",
"5 x 8 Rugs": "https://www.birchlane.com/rugs/sb0/5-x-8-rugs-c1873954.html",
"6 x 9 Rugs": "https://www.birchlane.com/rugs/sb0/6-x-9-rugs-c1873955.html",
"8 x 10 Rugs": "https://www.birchlane.com/rugs/sb0/8-x-10-rugs-c1873956.html",
"9 x 12 Rugs": "https://www.birchlane.com/rugs/sb0/9-x-12-rugs-c1873957.html",
"10 x 14 Rugs": "https://www.birchlane.com/rugs/sb0/10x14-rugs-c1873958.html",
"Blankets & Throws": "https://www.birchlane.com/decor-pillows/sb0/blankets-throws-c1805537.html",
"Outdoor Pillows": "https://www.birchlane.com/decor-pillows/sb0/outdoor-pillows-c1845350.html",
"Pillow Covers": "https://www.birchlane.com/decor-pillows/sb0/pillow-covers-c1873909.html",
"Throw Pillows": "https://www.birchlane.com/decor-pillows/sb0/throw-pillows-c1805538.html",
"Curtains & Drapes": "https://www.birchlane.com/wall-decor-mirrors/sb0/curtains-drapes-c1854788.html",
"Valances & Kitchen Curtains": "https://www.birchlane.com/wall-decor-mirrors/sb0/valances-kitchen-curtains-c1867256.html",
"Kitchen Aprons": "https://www.birchlane.com/kitchen-tabletop/sb0/kitchen-aprons-c1875383.html",
"Kitchen Towels": "https://www.birchlane.com/kitchen-tabletop/sb0/kitchen-towels-c1862678.html",
"Placemats, Chargers & Napkins": "https://www.birchlane.com/kitchen-tabletop/sb0/placemats-chargers-napkins-c1862679.html",
"Potholders": "https://www.birchlane.com/kitchen-tabletop/sb0/potholders-c1875384.html",
"Tablecloths & Runners": "https://www.birchlane.com/kitchen-tabletop/sb0/tablecloths-runners-c1862676.html",
"Baby Blankets": "https://www.birchlane.com/baby-kids/sb0/baby-blankets-c1877122.html",
"Crib Sheets": "https://www.birchlane.com/baby-kids/sb0/crib-sheets-c1872523.html",
"Crib Bedding Sets": "https://www.birchlane.com/baby-kids/sb0/crib-bedding-sets-c1869788.html",
"Changing Pads & Covers": "https://www.birchlane.com/baby-kids/sb0/changing-pads-covers-c1875491.html",
"Baby & Kids Rugs": "https://www.birchlane.com/baby-kids/sb0/baby-kids-rugs-c1877124.html",
"Outdoor Furniture Cushions": "https://www.birchlane.com/outdoor/sb0/outdoor-furniture-cushions-c1869989.html",
"Patio Furniture Covers": "https://www.birchlane.com/outdoor/sb0/patio-furniture-covers-c1869990.html",
}

STORAGE = {
"Boxes & Baskets": "https://www.birchlane.com/storage/sb0/boxes-baskets-c1875445.html",
"Closet Systems": "https://www.birchlane.com/storage/sb0/closet-systems-c1867228.html",
"Flatware & Kitchen Utensil Storage": "https://www.birchlane.com/storage/sb0/flatware-kitchen-utensil-storage-c1867265.html",
"Wine Racks": "https://www.birchlane.com/storage/sb0/wine-racks-c1869938.html",
"Knife Storage": "https://www.birchlane.com/kitchen-tabletop/sb0/knife-storage-c1875376.html",
"Desk Organizers": "https://www.birchlane.com/storage/sb0/desk-organizers-c1872481.html",
"Desks with Storage": "https://www.birchlane.com/storage/sb0/desks-with-storage-c1875458.html",
"Wall & Mail Organizers": "https://www.birchlane.com/storage/sb0/wall-mail-organizers-c1870095.html",
"Console Tables with Storage": "https://www.birchlane.com/storage/sb0/console-tables-with-storage-c1875440.html",
"Beds with Storage": "https://www.birchlane.com/storage/sb0/beds-with-storage-c1875448.html",
"Coffee Tables with Storage": "https://www.birchlane.com/storage/sb0/coffee-tables-with-storage-c1875442.html",
"Dressers": "https://www.birchlane.com/storage/sb0/dressers-c1875451.html",
"Bookcases": "https://www.birchlane.com/storage/sb0/bookcases-c1875443.html",
"Jewelry Armoires": "https://www.birchlane.com/storage/sb0/jewelry-armoires-c1869931.html",
"Nightstands with Storage": "https://www.birchlane.com/storage/sb0/nightstands-with-storage-c1875450.html",
"Laundry Baskets": "https://www.birchlane.com/bathroom/sb0/laundry-baskets-c1867229.html",
"Towel & Robe Hooks": "https://www.birchlane.com/storage/sb0/towel-robe-hooks-c1875469.html",
"Bathroom Cabinets & Shelves": "https://www.birchlane.com/bathroom/sb0/bathroom-cabinets-shelves-c1864511.html",
"Medicine Cabinets": "https://www.birchlane.com/bathroom/sb0/medicine-cabinets-c1870966.html",
"Holiday Storage": "https://www.birchlane.com/holiday/sb0/holiday-storage-c1871509.html",
}
